#!/bin/bash

python3 train.py \
    --model_name_or_path roberta-base \
    --train_file ../data/detector_data.json \
    --seed 42 \
    --balance_data True \
    --pad_to_max_length False \
    --validation_rate 0.02 \
    --learning_rate 2e-5 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 16 \
    --logging_strategy steps \
    --evaluation_strategy steps \
    --eval_steps 1000 \
    --save_steps 1000 \
    --logging_steps 100 \
    --load_best_model_at_end \
    --metric_for_best_model accuracy \
    --num_train_epochs 10 \
    --gradient_accumulation_steps 1 \
    --save_total_limit 2 \
    --input_column comment \
    --label_column classification \
    --max_seq_length 256 \
    --output_dir ../results/detectors/roberta-WITHOUT_CLASSIFICATION \
    --cache_dir .cache \
    --do_train \
    --do_eval \
    --focus_label WITHOUT_CLASSIFICATION \
    --num_labels 2 \
    --overwrite_output_dir \